apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-infra.dbServiceName" . }}
  labels:
    {{ include "todo-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
      name: postgres
