FROM python:3.11-slim AS builder

WORKDIR /app

COPY requirements.txt .
RUN pip install --target=/app/packages --no-cache-dir -r requirements.txt

FROM gcr.io/distroless/python3

WORKDIR /app

COPY --from=builder /app/packages /usr/local/lib/python3.11/site-packages
ENV PYTHONPATH=/usr/local/lib/python3.11/site-packages

COPY . .

EXPOSE 8000

CMD ["src/main.py"]
