config:
  otelExporterOtlpEndpoint: "http://host.docker.internal:14318/v1/traces"

todo:
  replicaCount: 1

ingress:
  hosts:
    - host: todo.local
      paths:
        - path: /
          pathType: Prefix
