nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

config:
  name: todo-app-config
  serverPort: "8080"
  serverHost: "0.0.0.0"

database:
  secretName: todo-app-secret

todo:
  deploymentName: todo-app
  serviceName: todo-app-service
  replicaCount: 3
  containerPort: 8080
  image:
    repository: ghcr.io/monyzik/idt-labs
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  databaseUrl: ""
  resources: {}

ingress:
  enabled: true
  name: todo-app-ingress
  className: nginx
  annotations: {}
  hosts:
    - host: todo.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
