{{- if .Values.database.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todo-app.dbPvcName" . }}
  labels:
    {{ include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    {{ toYaml .Values.database.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size | quote }}
  {{- with .Values.database.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
