{{- if and .Values.database.auth.createSecret (not .Values.database.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.dbSecretName" . }}
  labels:
    {{ include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.auth.password | quote }}
{{- end }}
