apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app.todoDeploymentName" . }}
  labels:
    {{ include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
    app: {{ include "todo-app.todoDeploymentName" . }}
spec:
  replicas: {{ .Values.todo.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "todo-app.todoDeploymentName" . }}
  template:
    metadata:
      labels:
        {{ include "todo-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: application
        app: {{ include "todo-app.todoDeploymentName" . }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "todo-app.todoDeploymentName" . }}
          image: "{{ .Values.todo.image.repository }}:{{ .Values.todo.image.tag }}"
          imagePullPolicy: {{ .Values.todo.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.todo.containerPort }}
              protocol: TCP
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todo-app.configMapName" . }}
                  key: APP_NAME
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todo-app.configMapName" . }}
                  key: SERVER_PORT
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todo-app.configMapName" . }}
                  key: SERVER_HOST
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "todo-app.secretName" . }}
                  key: DATABASE_URL
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todo-app.configMapName" . }}
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
          {{- with .Values.todo.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
