apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.todoServiceName" . }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
spec:
  type: {{ .Values.todo.service.type }}
  selector:
    app: {{ include "todo-app.todoDeploymentName" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.todo.service.port }}
      targetPort: {{ .Values.todo.containerPort }}
      name: http
